/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const srvbooks_Logic_Cud = require('./code/srvbooks-logic-cud');
const srvbooks_Logic_Read = require('./code/srvbooks-logic-Read');

class LCAP2211ECCCICDService extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'SrvBooks', async (request) => {
            await srvbooks_Logic_Cud({
                request
            });
        });

        this.after('READ', 'SrvBooks', async (results, request) => {
            await srvbooks_Logic_Read({
                results,
                request
            });
        });

        return super.init();
    }
}


module.exports = {
    LCAP2211ECCCICDService
};